# Generated by Django 4.2.9 on 2024-01-30 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes_instance', models.CharField(max_length=100)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.userprofile')),
            ],
        ),
    ]
