# Generated by Django 4.2.9 on 2024-01-31 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='project_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
