# Generated by Django 4.2.8 on 2024-01-18 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='asd1',
            new_name='images_count',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='asd2',
            new_name='project_create_time',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='asd3',
            new_name='project_name',
        ),
    ]
